/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50141
Source Host           : localhost:3306
Source Database       : ui_test

Target Server Type    : MYSQL
Target Server Version : 50141
File Encoding         : 65001

Date: 2015-04-10 17:35:39
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `t_uitest_cases`
-- ----------------------------
DROP TABLE IF EXISTS `t_uitest_cases`;
CREATE TABLE `t_uitest_cases` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `tc_key` varchar(200) NOT NULL DEFAULT '',
  `tc_value` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`id`,`tc_key`)
) ENGINE=MyISAM AUTO_INCREMENT=26 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of t_uitest_cases
-- ----------------------------
INSERT INTO `t_uitest_cases` VALUES ('1', 'LoginTest.UserNameIsEmptyTest', 'document.getElementById(\"uname\").value=\"\";document.getElementById(\"pword\").value=\"\";$(\'#loginForm\').submit()');
INSERT INTO `t_uitest_cases` VALUES ('2', 'LoginTest.PasswordIsEmptyTest', 'document.getElementById(\"uname\").value=\"13262505677\";document.getElementById(\"pword\").value=\"\";$(\'#loginForm\').submit()');
INSERT INTO `t_uitest_cases` VALUES ('3', 'LoginTest.PasswordIsWrongTest', 'document.getElementById(\"uname\").value=\"13262505677\";document.getElementById(\"pword\").value=\"999999\";$(\'#loginForm\').submit()');
INSERT INTO `t_uitest_cases` VALUES ('4', 'LoginTest.UserNameNotExistTest', 'document.getElementById(\"uname\").value=\"18888888888\";document.getElementById(\"pword\").value=\"111111\";$(\'#loginForm\').submit()');
INSERT INTO `t_uitest_cases` VALUES ('5', 'LoginTest.SolutionTest', 'document.getElementById(\"uname\").value=\"13291801308\";document.getElementById(\"pword\").value=\"111111\";$(\'#loginForm\').submit()');
INSERT INTO `t_uitest_cases` VALUES ('6', 'RegisterTest.RegisterTest', 'document.getElementById(\"regName\").value=\"\\u5149\\u5251\\u79D1\\u6280\\u6709\\u9650\\u516C\\u53F8\";document.getElementById(\"regPhone\").value=\"13291801306\";document.getElementById(\"regCode\").value=\"123456\";document.getElementById(\"regPwd\").value=\"123456789\";document.getElementById(\"regConfimPwd\").value=\"123456789\";$(\'#agreeCheck\').click()');
INSERT INTO `t_uitest_cases` VALUES ('7', 'MemberRegister.SolutionTest', 'document.getElementById(\"name\").value=\"光剑科技有限公司\";document.getElementById(\"corp\").value=1;document.getElementById(\"address\").value=\"滨江区秋意路234号\";document.getElementById(\"regCode\").value=\"1111111111111\";document.getElementById(\"legal\").value=\"陈光剑\";document.getElementById(\"certId\").value=\"320722198905096914\";document.getElementById(\"contact\").value=\"陈光剑\";document.getElementById(\"mobile\").value=\"13291801306\";document.getElementById(\"email\").value=\"universsky@163.com\";document.getElementsByClassName(\'type-model\')[0].value=\'电梯系统\';document.getElementsByClassName(\'type-company\')[0].value=\'光剑电梯系统公司\'');
INSERT INTO `t_uitest_cases` VALUES ('8', 'MemberRegister.Company3Words', 'document.getElementById(\"name\").value=\"光剑科\";document.getElementById(\"corp\").value=1;document.getElementById(\"address\").value=\"滨江区秋意路234号\";document.getElementById(\"regCode\").value=\"1111111111111\";document.getElementById(\"legal\").value=\"陈光剑\";document.getElementById(\"certId\").value=\"320722198905096914\";document.getElementById(\"contact\").value=\"陈光剑\";document.getElementById(\"mobile\").value=\"13291801306\";document.getElementById(\"email\").value=\"universsky@163.com\";document.getElementsByClassName(\'type-model\')[0].value=\'电梯系统\';document.getElementsByClassName(\'type-company\')[0].value=\'光剑电梯系统公司\'');
INSERT INTO `t_uitest_cases` VALUES ('9', 'MemberRegister.Company26Words', 'document.getElementById(\"name\").value=\"光剑科技有限公司光剑科技有限公司光剑科技有限公司光剑\";document.getElementById(\"corp\").value=1;document.getElementById(\"address\").value=\"滨江区秋意路234号\";document.getElementById(\"regCode\").value=\"1111111111111\";document.getElementById(\"legal\").value=\"陈光剑\";document.getElementById(\"certId\").value=\"320722198905096914\";document.getElementById(\"contact\").value=\"陈光剑\";document.getElementById(\"mobile\").value=\"13291801306\";document.getElementById(\"email\").value=\"universsky@163.com\";document.getElementsByClassName(\'type-model\')[0].value=\'电梯系统\';document.getElementsByClassName(\'type-company\')[0].value=\'光剑电梯系统公司\'');
INSERT INTO `t_uitest_cases` VALUES ('10', 'MemberRegister.CompanyEnglishName', 'document.getElementById(\"name\").value=\"Apple\";document.getElementById(\"corp\").value=1;document.getElementById(\"address\").value=\"滨江区秋意路234号\";document.getElementById(\"regCode\").value=\"1111111111111\";document.getElementById(\"legal\").value=\"陈光剑\";document.getElementById(\"certId\").value=\"320722198905096914\";document.getElementById(\"contact\").value=\"陈光剑\";document.getElementById(\"mobile\").value=\"13291801306\";document.getElementById(\"email\").value=\"universsky@163.com\";document.getElementsByClassName(\'type-model\')[0].value=\'电梯系统\';document.getElementsByClassName(\'type-company\')[0].value=\'光剑电梯系统公司\'');
INSERT INTO `t_uitest_cases` VALUES ('11', 'MemberRegister.CompanyIllegalChars', 'document.getElementById(\"name\").value=\"!@#$%^&\";document.getElementById(\"corp\").value=1;document.getElementById(\"address\").value=\"滨江区秋意路234号\";document.getElementById(\"regCode\").value=\"1111111111111\";document.getElementById(\"legal\").value=\"陈光剑\";document.getElementById(\"certId\").value=\"320722198905096914\";document.getElementById(\"contact\").value=\"陈光剑\";document.getElementById(\"mobile\").value=\"13291801306\";document.getElementById(\"email\").value=\"universsky@163.com\";document.getElementsByClassName(\'type-model\')[0].value=\'电梯系统\';document.getElementsByClassName(\'type-company\')[0].value=\'光剑电梯系统公司\'');
INSERT INTO `t_uitest_cases` VALUES ('12', 'MemberRegister.AddressNull', 'document.getElementById(\"name\").value=\"光剑科技有限公司\";document.getElementById(\"corp\").value=1;document.getElementById(\"address\").value=\"\";document.getElementById(\"regCode\").value=\"1111111111111\";document.getElementById(\"legal\").value=\"陈光剑\";document.getElementById(\"certId\").value=\"320722198905096914\";document.getElementById(\"contact\").value=\"陈光剑\";document.getElementById(\"mobile\").value=\"13291801306\";document.getElementById(\"email\").value=\"universsky@163.com\";document.getElementsByClassName(\'type-model\')[0].value=\'电梯系统\';document.getElementsByClassName(\'type-company\')[0].value=\'光剑电梯系统公司\'');
INSERT INTO `t_uitest_cases` VALUES ('13', 'MemberRegister.RegCodeNull', 'document.getElementById(\"name\").value=\"光剑科技有限公司\";document.getElementById(\"corp\").value=1;document.getElementById(\"address\").value=\"滨江区秋意路234号\";document.getElementById(\"regCode\").value=\"\";document.getElementById(\"legal\").value=\"陈光剑\";document.getElementById(\"certId\").value=\"320722198905096914\";document.getElementById(\"contact\").value=\"陈光剑\";document.getElementById(\"mobile\").value=\"13291801306\";document.getElementById(\"email\").value=\"universsky@163.com\";document.getElementsByClassName(\'type-model\')[0].value=\'电梯系统\';document.getElementsByClassName(\'type-company\')[0].value=\'光剑电梯系统公司\'');
INSERT INTO `t_uitest_cases` VALUES ('14', 'MemberRegister.RegCode1Digits', 'document.getElementById(\"name\").value=\"光剑科技有限公司\";document.getElementById(\"corp\").value=1;document.getElementById(\"address\").value=\"滨江区秋意路234号\";document.getElementById(\"regCode\").value=\"1\";document.getElementById(\"legal\").value=\"陈光剑\";document.getElementById(\"certId\").value=\"320722198905096914\";document.getElementById(\"contact\").value=\"陈光剑\";document.getElementById(\"mobile\").value=\"13291801306\";document.getElementById(\"email\").value=\"universsky@163.com\";document.getElementsByClassName(\'type-model\')[0].value=\'电梯系统\';document.getElementsByClassName(\'type-company\')[0].value=\'光剑电梯系统公司\'');
INSERT INTO `t_uitest_cases` VALUES ('15', 'MemberRegister.RegCode14Digits', 'document.getElementById(\"name\").value=\"光剑科技有限公司\";document.getElementById(\"corp\").value=1;document.getElementById(\"address\").value=\"滨江区秋意路234号\";document.getElementById(\"regCode\").value=\"11111111111112\";document.getElementById(\"legal\").value=\"陈光剑\";document.getElementById(\"certId\").value=\"320722198905096914\";document.getElementById(\"contact\").value=\"陈光剑\";document.getElementById(\"mobile\").value=\"13291801306\";document.getElementById(\"email\").value=\"universsky@163.com\";document.getElementsByClassName(\'type-model\')[0].value=\'电梯系统\';document.getElementsByClassName(\'type-company\')[0].value=\'光剑电梯系统公司\'');
INSERT INTO `t_uitest_cases` VALUES ('16', 'MemberRegister.Address20Words', 'document.getElementById(\"name\").value=\"光剑科技有限公司\";document.getElementById(\"corp\").value=1;document.getElementById(\"address\").value=\"滨江区滨江区滨江区滨江区滨江区滨江区滨江\";document.getElementById(\"regCode\").value=\"1111111111111\";document.getElementById(\"legal\").value=\"陈光剑\";document.getElementById(\"certId\").value=\"320722198905096914\";document.getElementById(\"contact\").value=\"陈光剑\";document.getElementById(\"mobile\").value=\"13291801306\";document.getElementById(\"email\").value=\"universsky@163.com\";document.getElementsByClassName(\'type-model\')[0].value=\'电梯系统\';document.getElementsByClassName(\'type-company\')[0].value=\'光剑电梯系统公司\'');
INSERT INTO `t_uitest_cases` VALUES ('17', 'MemberRegister.Address51Words', 'document.getElementById(\"name\").value=\"光剑科技有限公司\";document.getElementById(\"corp\").value=1;document.getElementById(\"address\").value=\"滨江区滨江区滨江区滨江区滨江区滨江区滨江区滨江区滨江区滨江区滨江区滨江区滨江区滨江区滨江区滨江区滨江区\";document.getElementById(\"regCode\").value=\"1111111111111\";document.getElementById(\"legal\").value=\"陈光剑\";document.getElementById(\"certId\").value=\"320722198905096914\";document.getElementById(\"contact\").value=\"陈光剑\";document.getElementById(\"mobile\").value=\"13291801306\";document.getElementById(\"email\").value=\"universsky@163.com\";document.getElementsByClassName(\'type-model\')[0].value=\'电梯系统\';document.getElementsByClassName(\'type-company\')[0].value=\'光剑电梯系统公司\'');
INSERT INTO `t_uitest_cases` VALUES ('18', 'MemberRegister.Address3Words', 'document.getElementById(\"name\").value=\"光剑科技有限公司\";document.getElementById(\"corp\").value=1;document.getElementById(\"address\").value=\"滨江区\";document.getElementById(\"regCode\").value=\"1111111111111\";document.getElementById(\"legal\").value=\"陈光剑\";document.getElementById(\"certId\").value=\"320722198905096914\";document.getElementById(\"contact\").value=\"陈光剑\";document.getElementById(\"mobile\").value=\"13291801306\";document.getElementById(\"email\").value=\"universsky@163.com\";document.getElementsByClassName(\'type-model\')[0].value=\'电梯系统\';document.getElementsByClassName(\'type-company\')[0].value=\'光剑电梯系统公司\'');
INSERT INTO `t_uitest_cases` VALUES ('19', 'MemberRegister.Legal6Words', 'document.getElementById(\"name\").value=\"光剑科技有限公司\";document.getElementById(\"corp\").value=1;document.getElementById(\"address\").value=\"滨江区秋意路234号\";document.getElementById(\"regCode\").value=\"1111111111111\";document.getElementById(\"legal\").value=\"陈光剑陈光剑\";document.getElementById(\"certId\").value=\"320722198905096914\";document.getElementById(\"contact\").value=\"陈光剑\";document.getElementById(\"mobile\").value=\"13291801306\";document.getElementById(\"email\").value=\"universsky@163.com\";document.getElementsByClassName(\'type-model\')[0].value=\'电梯系统\';document.getElementsByClassName(\'type-company\')[0].value=\'光剑电梯系统公司\'');
INSERT INTO `t_uitest_cases` VALUES ('20', 'MemberRegister.Legal5Words', 'document.getElementById(\"name\").value=\"光剑科技有限公司\";document.getElementById(\"corp\").value=1;document.getElementById(\"address\").value=\"滨江区秋意路234号\";document.getElementById(\"regCode\").value=\"1111111111111\";document.getElementById(\"legal\").value=\"陈光剑陈光\";document.getElementById(\"certId\").value=\"320722198905096914\";document.getElementById(\"contact\").value=\"陈光剑\";document.getElementById(\"mobile\").value=\"13291801306\";document.getElementById(\"email\").value=\"universsky@163.com\";document.getElementsByClassName(\'type-model\')[0].value=\'电梯系统\';document.getElementsByClassName(\'type-company\')[0].value=\'光剑电梯系统公司\'');
INSERT INTO `t_uitest_cases` VALUES ('21', 'MemberRegister.Legal1Words', 'document.getElementById(\"name\").value=\"光剑科技有限公司\";document.getElementById(\"corp\").value=1;document.getElementById(\"address\").value=\"滨江区秋意路234号\";document.getElementById(\"regCode\").value=\"1111111111111\";document.getElementById(\"legal\").value=\"陈\";document.getElementById(\"certId\").value=\"320722198905096914\";document.getElementById(\"contact\").value=\"陈光剑\";document.getElementById(\"mobile\").value=\"13291801306\";document.getElementById(\"email\").value=\"universsky@163.com\";document.getElementsByClassName(\'type-model\')[0].value=\'电梯系统\';document.getElementsByClassName(\'type-company\')[0].value=\'光剑电梯系统公司\'');
INSERT INTO `t_uitest_cases` VALUES ('22', 'MemberRegister.LegalNull', 'document.getElementById(\"name\").value=\"光剑科技有限公司\";document.getElementById(\"corp\").value=1;document.getElementById(\"address\").value=\"滨江区秋意路234号\";document.getElementById(\"regCode\").value=\"1111111111111\";document.getElementById(\"legal\").value=\"\";document.getElementById(\"certId\").value=\"320722198905096914\";document.getElementById(\"contact\").value=\"陈光剑\";document.getElementById(\"mobile\").value=\"13291801306\";document.getElementById(\"email\").value=\"universsky@163.com\";document.getElementsByClassName(\'type-model\')[0].value=\'电梯系统\';document.getElementsByClassName(\'type-company\')[0].value=\'光剑电梯系统公司\'');
INSERT INTO `t_uitest_cases` VALUES ('23', 'LoginTest.SolutionTestNotMemberRegistered', 'document.getElementById(\"uname\").value=\"13288888884\";document.getElementById(\"pword\").value=\"111111\";$(\'#loginForm\').submit()');
INSERT INTO `t_uitest_cases` VALUES ('24', 'LoginTest.SolutionTestMemberRegistered', 'document.getElementById(\"uname\").value=\"13291801308\";document.getElementById(\"pword\").value=\"111111\";$(\'#loginForm\').submit()');
INSERT INTO `t_uitest_cases` VALUES ('25', 'PartnerManage.AddPartner', '$(\'#addParter\').click();$(\'#parterType\').val(\'电梯系统\');$(\'#company\').val(\'光剑电梯系统供应商\');$(\'.dialog_form_btn\')[1].click()');

-- ----------------------------
-- Table structure for `t_uitest_result`
-- ----------------------------
DROP TABLE IF EXISTS `t_uitest_result`;
CREATE TABLE `t_uitest_result` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `tc_key` varchar(100) NOT NULL,
  `timestamp` char(14) NOT NULL,
  `img_name` varchar(200) NOT NULL,
  `tc_result` varchar(20) NOT NULL,
  `expected` varchar(1000) DEFAULT NULL,
  `actual` varchar(1000) DEFAULT NULL,
  `log` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=341 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

-- ----------------------------
-- Records of t_uitest_result
-- ----------------------------

INSERT INTO `t_uitest_result` VALUES ('321', 'RegisterTest.RegisterTest', '20150410102705', '20150410102705_RegisterTest.RegisterTest.jpeg', 'PASS', 'true', 'true', '');
INSERT INTO `t_uitest_result` VALUES ('322', 'MemberRegister.SolutionTest', '20150410102705', '20150410102705_MemberRegister.SolutionTest.jpeg', 'PASS', 'http://dev.qjdchina.com/front/member/apply.htm', 'http://dev.qjdchina.com/front/member/apply.htm', 'Current url===============http://dev.qjdchina.com/front/member/apply.htm');
INSERT INTO `t_uitest_result` VALUES ('323', 'MemberRegister.CompanyEnglishName', '20150410102705', '20150410102705_MemberRegister.CompanyEnglishName.jpeg', 'PASS', 'http://dev.qjdchina.com/front/member/apply.htm', 'http://dev.qjdchina.com/front/member/apply.htm', 'Current url===============http://dev.qjdchina.com/front/member/apply.htm');
INSERT INTO `t_uitest_result` VALUES ('324', 'MemberRegister.Company3Words', '20150410102705', '20150410102705_MemberRegister.Company3Words.jpeg', 'PASS', 'http://dev.qjdchina.com/front/member/apply.htm', 'http://dev.qjdchina.com/front/member/apply.htm', 'Current url===============http://dev.qjdchina.com/front/member/apply.htm');
INSERT INTO `t_uitest_result` VALUES ('325', 'MemberRegister.Company26Words', '20150410102705', '20150410102705_MemberRegister.Company26Words.jpeg', 'PASS', 'http://dev.qjdchina.com/front/member/apply.htm', 'http://dev.qjdchina.com/front/member/apply.htm', 'Current url===============http://dev.qjdchina.com/front/member/apply.htm');
INSERT INTO `t_uitest_result` VALUES ('326', 'MemberRegister.CompanyIllegalChars', '20150410102705', '20150410102705_MemberRegister.CompanyIllegalChars.jpeg', 'PASS', 'http://dev.qjdchina.com/front/member/apply.htm', 'http://dev.qjdchina.com/front/member/apply.htm', 'Current url===============http://dev.qjdchina.com/front/member/apply.htm');
INSERT INTO `t_uitest_result` VALUES ('327', 'MemberRegister.Address3Words', '20150410102705', '20150410102705_MemberRegister.Address3Words.jpeg', 'PASS', 'http://dev.qjdchina.com/front/member/apply.htm', 'http://dev.qjdchina.com/front/member/apply.htm', 'Current url===============http://dev.qjdchina.com/front/member/apply.htm');
INSERT INTO `t_uitest_result` VALUES ('328', 'MemberRegister.Address51Words', '20150410102705', '20150410102705_MemberRegister.Address51Words.jpeg', 'PASS', 'http://dev.qjdchina.com/front/member/apply.htm', 'http://dev.qjdchina.com/front/member/apply.htm', 'Current url===============http://dev.qjdchina.com/front/member/apply.htm');
INSERT INTO `t_uitest_result` VALUES ('329', 'MemberRegister.Address20Words', '20150410102705', '20150410102705_MemberRegister.Address20Words.jpeg', 'PASS', 'http://dev.qjdchina.com/front/member/apply.htm', 'http://dev.qjdchina.com/front/member/apply.htm', 'Current url===============http://dev.qjdchina.com/front/member/apply.htm');
INSERT INTO `t_uitest_result` VALUES ('330', 'MemberRegister.AddressNull', '20150410102705', '20150410102705_MemberRegister.AddressNull.jpeg', 'PASS', 'http://dev.qjdchina.com/front/member/apply.htm', 'http://dev.qjdchina.com/front/member/apply.htm', 'Current url===============http://dev.qjdchina.com/front/member/apply.htm');
INSERT INTO `t_uitest_result` VALUES ('331', 'MemberRegister.RegCode14Digits', '20150410102705', '20150410102705_MemberRegister.RegCode14Digits.jpeg', 'PASS', 'http://dev.qjdchina.com/front/member/apply.htm', 'http://dev.qjdchina.com/front/member/apply.htm', 'Current url===============http://dev.qjdchina.com/front/member/apply.htm');
INSERT INTO `t_uitest_result` VALUES ('332', 'MemberRegister.RegCode1Digits', '20150410102705', '20150410102705_MemberRegister.RegCode1Digits.jpeg', 'PASS', 'http://dev.qjdchina.com/front/member/apply.htm', 'http://dev.qjdchina.com/front/member/apply.htm', 'Current url===============http://dev.qjdchina.com/front/member/apply.htm');
INSERT INTO `t_uitest_result` VALUES ('333', 'MemberRegister.RegCodeNull', '20150410102705', '20150410102705_MemberRegister.RegCodeNull.jpeg', 'PASS', 'http://dev.qjdchina.com/front/member/apply.htm', 'http://dev.qjdchina.com/front/member/apply.htm', 'Current url===============http://dev.qjdchina.com/front/member/apply.htm');
INSERT INTO `t_uitest_result` VALUES ('334', 'MemberRegister.Legal1Words', '20150410102705', '20150410102705_MemberRegister.Legal1Words.jpeg', 'PASS', 'http://dev.qjdchina.com/front/member/apply.htm', 'http://dev.qjdchina.com/front/member/apply.htm', 'Current url===============http://dev.qjdchina.com/front/member/apply.htm');
INSERT INTO `t_uitest_result` VALUES ('335', 'MemberRegister.Legal5Words', '20150410102705', '20150410102705_MemberRegister.Legal5Words.jpeg', 'PASS', 'http://dev.qjdchina.com/front/member/apply.htm', 'http://dev.qjdchina.com/front/member/apply.htm', 'Current url===============http://dev.qjdchina.com/front/member/apply.htm');
INSERT INTO `t_uitest_result` VALUES ('336', 'MemberRegister.Legal6Words', '20150410102705', '20150410102705_MemberRegister.Legal6Words.jpeg', 'PASS', 'http://dev.qjdchina.com/front/member/apply.htm', 'http://dev.qjdchina.com/front/member/apply.htm', 'Current url===============http://dev.qjdchina.com/front/member/apply.htm');
INSERT INTO `t_uitest_result` VALUES ('337', 'MemberRegister.LegalNull', '20150410102705', '20150410102705_MemberRegister.LegalNull.jpeg', 'PASS', 'http://dev.qjdchina.com/front/member/apply.htm', 'http://dev.qjdchina.com/front/member/apply.htm', 'Current url===============http://dev.qjdchina.com/front/member/apply.htm');
INSERT INTO `t_uitest_result` VALUES ('338', 'PartnerManage.AddPartner', '20150410142803', '20150410142803_PartnerManage.AddPartner.jpeg', 'PASS', '光剑电梯系统供应商', '光剑电梯系统供应商', '嘀嗒嘀嗒ddddwewewe5645656444444441光剑电梯系统供应商');
INSERT INTO `t_uitest_result` VALUES ('339', 'PartnerManage.AddPartner', '20150410143824', '20150410143824_PartnerManage.AddPartner.jpeg', 'PASS', '光剑电梯系统供应商', '光剑电梯系统供应商', '嘀嗒嘀嗒\ndddd\nwewewe\n5645656\n44444444\n1\n光剑电梯系统供应商\n');
INSERT INTO `t_uitest_result` VALUES ('340', 'LoginTest.SolutionTest', '20150410173308', '20150410173308_LoginTest.SolutionTest.jpeg', 'PASS', 'default', 'default', 'Cookies===============[login_corpname=default; path=/; domain=dev.qjdchina.com, Hm_lvt_83af4d60fe4ee2fa7715be9b321264a0=1428658385; expires=星期六, 09 四月 2016 05:33:05 CST; path=/; domain=.qjdchina.com, Hm_lpvt_83af4d60fe4ee2fa7715be9b321264a0=1428658385; path=/; domain=.qjdchina.com, login_username=13291801308; path=/; domain=dev.qjdchina.com, JSESSIONID=B3892F6340E8663D6FE00E2B6A1B106E; path=/front/; domain=dev.qjdchina.com]');
